name: CI

on: [push, pull_request]

jobs:
  CI:
    name: continuos integration
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, ubuntu-latest, macos-latest, windows-latest]
        arch: [x86, x64]
        go: ['1.14']

    runs-on: ${{ matrix.os }}
    steps:

      - name: check out code
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.26

      - name: set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: build
        run: go build

      - name: test
        run: go test -v -coverprofile=profile.cov

      - name: send coverage goveralls
        uses: shogo82148/actions-goveralls@v1.4.0
        with:
          path-to-profile: profile.cov