name: CI

on: [push, pull_request]

jobs:
  CI:
    name: continuos integration
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, ubuntu-latest, macos-latest, windows-latest]
        arch: [x86, x64]
        go: ['1.14']

    runs-on: ${{ matrix.os }}
    steps:

      - name: check out code
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.26

      - name: set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: build
        run: go build

      - name: test
        run: go test -v -covermode=count -coverprofile=coverage.out

      - name: convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.0
        with:
          infile: coverage.out
          outfile: coverage.lcov

      - name: coveralls
        uses: coverallsapp/github-action@v1.0.2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov